language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: Techcable
  password:
    secure: RoKV2TBFqnCZkxu2nRKUR3NIECit6AgE5G17BS9qGjg7wkyimGZD34PsSyPV6gC1Ow5pSxAG2sS4+KqnGyQjCf67/FbVOi97tGS+R4TM+wU/x3pSkAMmM11XqPRy/FNGC5+Gjy3BZWCp01UHYHTZZf1d/OturCr08HSBq+nGXUMrbdLoZCPGz70GqW4FLodZ8sdeRV4E19B38nCfYb3HF7288u5oZiQZ73fP8Z+jm/Flrl0alKkqoxfWTtxXrtbaksdiOATJWJeV3bIspIrqETTC57nQoJj4NERuc/h9h03WF3qTgggOFnvmoKCO0lgqo9UAp6XVG/vjuCf83uKeLffomnOogsC0NsFdZ3rQ/jQ3J6n2YZZa4eEqttvJpDMWwl70osdY901psGjYPvshc+xsmsrLqCBCMNkzcMlPumbd3Itst50YZN8FJqBECTKZ6ssPyrw3+zS0lYDWQNFidxydE7CeQYOrQ+moe8PWVaq/YC0k/K1PD66t7IkZ3gJwkIGl51sVOVkhixvnZdzp1HmT5TsQNm4Q5u69vXx87nP3kI+qGh4e31mus9oPDe+AC9uOG2P5Z4FgxmYeWmOupaJaOGG69KbYHjnIrB0DtMxx76LlhhJ/lIC1xUvJ3FjSpJrOmotMt2Nj7W82BHF7iidoSOVmc6l59LLAQNkqaB0=
  on:
    tags: true
cache: pip
before_install:
    - eval "${MATRIX_EVAL}"
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7"

